apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260507-190210-8tpsc3h0nc59-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260507-190210-8tpsc3h0nc59.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260507-190210-8tpsc3h0nc59-service
            port:
              number: 80
