apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260507-190210-8tpsc3h0nc59-service
spec:
  selector:
    app: enterprise-system-20260507-190210-8tpsc3h0nc59
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
